import { theme, ThemeConfig } from 'antd';

export const COLORS = {
    BRAND: {
        B1: '#CAD9FF',
        B2: '#95B3FF',
        B3: '#608DFF',
        B4: '#2B66FD',
        B5: '#204DBE',
        B6: '#15347F',
        B7: '#0A1B40',
        B8: '#1E253C',
    },
    NEUTRAL: {
        N1: '#FFFFFF',
        N2: '#EFEFF0',
        N3: '#BFBFC1',
        N4: '#9F9FA2',
        N5: '#7F7F83',
        N6: '#5F5F64',
        N7: '#3F3F45',
        N8: '#1F1F26',
        N9: '#00000A',
    },
    GREEN: {
        G1: '#23C343',
        G2: '#00B42A',
        G3: '#0C7828',
        G4: '#135B28',
        G5: '#193D27',
        G6: '#1F2F29',
    },
    ORANGE: {
        O1: '#FF9A2E',
        O2: '#FF7D00',
        O3: '#A5570F',
        O4: '#794517',
        O5: '#4C321E',
        O6: '#352B27',
    },
    RED: {
        R1: '#F57373',
        R2: '#F25050',
        R3: '#9E3C3F',
        R4: '#733337',
        R5: '#49292E',
        R6: '#34282E',
    },
};

export const DARK: ThemeConfig = {
    token: {
        motion: false,
        colorPrimaryBg: '#0a1b40',
        colorPrimaryBorder: '#608dff',
        colorPrimaryBorderHover: '#2b66fd',
        colorPrimaryHover: '#204dbe',
        colorPrimary: '#2b66fd',
        colorInfo: '#2b66fd',
        colorPrimaryActive: '#15347f',
        colorPrimaryTextHover: '#2b66fd',
        colorPrimaryText: '#608dff',
        colorPrimaryTextActive: '#2b66fd',
        colorLink: '#608dff',
        colorText: '#ffffff',
        colorTextSecondary: '#dbdbdb',
        colorTextTertiary: '#b7b7b7',
        colorSuccess: '#00b42a',
        colorSuccessText: '#23c343',
        colorSuccessBorder: '#00b42a66',
        colorSuccessTextHover: '#00b42a',
        colorSuccessTextActive: '#009a29',
        colorWarning: '#ff7d00',
        colorWarningTextHover: '#ff7d00',
        colorWarningText: '#ff9a2e',
        colorWarningTextActive: '#d27400',
        colorWarningBg: '#ff7d0033',
        colorWarningBorder: '#ff7d0066',
        colorError: '#f25050',
        colorErrorTextActive: '#d64035',
        colorErrorText: '#f57373',
        colorErrorTextHover: '#f25050',
        colorErrorBg: '#f2505033',
        colorErrorBorder: '#f2505066',
        colorLinkHover: '#2b66fd',
        colorLinkActive: '#2b66fd',
        colorTextQuaternary: '#939393',
        colorTextHeading: '#6F6F6F',
        colorTextLabel: '#6F6F6F',
        colorBorder: '#4b4b4b',
        colorBorderSecondary: '#1c1c1c',
        colorBgElevated: '#1c1c1c',
        colorBgSpotlight: '#1c1c1c',
        colorBgMask: '#0000007a',
        colorBgContainer: '#000000',
        colorBgLayout: '#000000',
        wireframe: false,
        colorPrimaryBgHover: '#000000',
        colorFill: '#1c1c1c',
        boxShadowSecondary: '0',
        borderRadius: 4,
    },
    components: {
        Button: {
            primaryShadow: 'none',
            colorPrimary: '#0065FD',
            borderRadius: 4,
        },
        Drawer: {
            colorBgElevated: COLORS.NEUTRAL.N8,
        },
        Table: {
            // motion: false,
            colorBgContainer: 'transparent',
            // colorTextLightSolid: '#DBDBDB',
            // rowHoverBg: 'rgba(255, 255, 255, 0.12)',
            colorText: '#EFEFF0',
            cellPaddingBlock: 13,
            borderColor: '#3F3F45',
            headerBg: 'transparent',
            headerColor: COLORS.NEUTRAL.N3,
        },
        Modal: {
            colorBgMask: 'rgba(0, 0, 10, 1)',
            colorBgElevated: '#3F3F45',
            titleColor: '#FFFFFF',
            colorText: '#FFFFFF',
        },
        Input: {
            colorBgContainer: COLORS.NEUTRAL.N8,
            colorBorder: COLORS.NEUTRAL.N7,
            colorText: COLORS.NEUTRAL.N1,
            activeBorderColor: COLORS.BRAND.B4,
            hoverBorderColor: COLORS.BRAND.B4,
            activeShadow: '0',
            controlHeight: 32,
        },
        Form: {
            labelColor: 'rgba(239, 239, 240, 1)',
            verticalLabelPadding: 4,
        },
        Card: {
            colorBgContainer: 'black',
            colorText: '#FFF',
            colorBorderSecondary: 'rgb(75, 75, 75)',
        },
        Descriptions: {
            colorText: 'rgb(224, 224, 224)',
        },
        Radio: {
            colorPrimary: 'rgb(96, 141, 255)',
            colorPrimaryHover: 'rgb(96, 141, 255)',
            colorBorder: '#4B4B4B',
        },
        Select: {
            colorBgContainer: 'transparent',
            colorBorder: COLORS.NEUTRAL.N7,
            colorText: COLORS.NEUTRAL.N2,
            multipleItemBg: 'rgba(255, 255, 255, 0.08)',
            optionSelectedBg: 'rgba(255, 255, 255, 0.08)',
            optionActiveBg: 'rgba(255, 255, 255, 0.08)',
            colorBgElevated: 'rgba(63,63,69,0.6)',
            boxShadowSecondary: '0',
            controlOutline: '0',
            colorTextPlaceholder: COLORS.NEUTRAL.N5,
            controlHeight: 36,
            borderRadius: 6,
        },
        Menu: {
            itemBg: 'black',
            itemActiveBg: '#1F1F26',
            itemHoverColor: 'white',
            itemHoverBg: '#1F1F26',
            itemSelectedBg: '#1F1F26',
            itemSelectedColor: 'white',
        },
        Cascader: {
            colorPrimary: 'rgb(96, 141, 255)',
            colorText: '#DBDBDB',
            colorBorder: '#4B4B4B',
            colorTextQuaternary: '#4B4B4B',
            optionSelectedBg: 'rgba(255, 255, 255, 0.08)',
            dropdownHeight: 160,
            colorBgContainer: 'rgba(63,63,69,0.6)',
        },
        TreeSelect: {
            colorPrimary: 'rgb(96, 141, 255)',
            colorText: '#DBDBDB',
            colorBorder: '#4B4B4B',
            colorTextQuaternary: '#4B4B4B',
            colorBgContainer: 'rgba(63,63,69,0.6)',
        },
        InputNumber: {
            colorBorder: '#3f3f46',
            addonBg: 'transparent',
            colorBgContainer: 'transparent',
            controlHeight: 36,
            paddingBlock: 6,
            activeShadow: 'none',
            handleVisible: true,
            handleWidth: 34,
            hoverBorderColor: '#3f3f46',
        },
        Popover: {
            colorBgElevated: 'rgba(63, 63, 69, 0.60)',
            borderRadius: 4,
        },
        DatePicker: {
            colorBgElevated: '#0a1b40',
            colorBgContainer: '#0a1b40',
            colorText: '#DBDBDB',
        },
        Tree: {
            titleHeight: 32,
            nodeHoverBg: 'rgba(63, 63, 69, 0.8)',
            nodeSelectedBg: 'rgba(63, 63, 69, 0.4)',
            fontSize: 12,
        },
        Collapse: {
            contentBg: 'transparent',
        },
        Slider: {
            dotBorderColor: 'rgba(255, 255, 255, 0.08)',
        },
    },
    algorithm: theme.darkAlgorithm,
};
