import { theme, ThemeConfig } from 'antd';

export const COLORS = {
    BRAND: {
        B1: '#E5F0FF',
        B2: '#BED8FD',
        B3: '#98C1FD',
        B4: '#72AAFD',
        B5: '#4C93FD',
        B6: '#267CFD',
        B7: '#0065FD',
        B8: '#0055D8',
    },
    NEUTRAL: {
        N1: '#00000A',
        N2: '#1F1F26',
        N3: '#3F3F45',
        N4: '#5F5F64',
        N5: '#7F7F83',
        N6: '#9F9FA2',
        N7: '#BFBFC1',
        N8: '#FFFFFF',
        N9: '#DFDFE0',
    },
    GREEN: {
        G1: '#00B42A',
        G2: '#23C343',
        G3: '#009A29',
        G4: '#7BE188',
        G5: '#AFF0B5',
        G6: '#E8FFEA',
    },
    ORANGE: {
        O1: '#FF7D00',
        O2: '#FF9A2E',
        O3: '#D25F00',
        O4: '#FFCF8B',
        O5: '#FFE4BA',
        O6: '#FFF4E0',
    },
    RED: {
        R1: '#F25050',
        R2: '#F57373',
        R3: '#D63535',
        R4: '#F79696',
        R5: '#FBCACA',
        R6: '#FEEDED',
    },
};

export const LIGHT: ThemeConfig = {
    token: {
        motion: false,
        colorPrimaryBg: '#e5f0ff',
        colorPrimaryBorder: '#0065fd',
        colorPrimaryBorderHover: '#3384fd',
        colorPrimaryHover: '#3384fd',
        colorPrimary: '#0065fd',
        colorInfo: '#0065fd',
        colorPrimaryActive: '#0051ca',
        colorPrimaryTextHover: '#3384fd',
        colorPrimaryText: '#0065fd',
        colorPrimaryTextActive: '#0051ca',
        colorLink: '#0065fd',
        colorText: '#202d40',
        colorTextSecondary: '#4c576c',
        colorTextTertiary: '#8592a6',
        colorSuccess: '#00b42a',
        colorSuccessText: '#00b42a',
        colorSuccessBorder: '#aff0b5',
        colorSuccessTextHover: '#23c343',
        colorSuccessTextActive: '#009a29',
        colorWarning: '#ff7d00',
        colorWarningTextHover: '#ff9a2e',
        colorWarningText: '#ff7d00',
        colorWarningTextActive: '#d25f00',
        colorWarningBg: '#fff4e0',
        colorWarningBorder: '#ffe4ba',
        colorError: '#f25050',
        colorErrorTextActive: '#d63535',
        colorErrorText: '#f25050',
        colorErrorTextHover: '#f57373',
        colorErrorBg: '#feeded',
        colorErrorBorder: '#fbcaca',
        colorLinkHover: '#2b66fd',
        colorLinkActive: '#2b66fd',
        colorTextQuaternary: '#ccd4e2',
        colorBorder: '#ccd4e2',
        colorBorderSecondary: '#dfe5f0',
        colorBgElevated: '#ffffff',
        colorBgSpotlight: '#ffffff',
        colorBgMask: '#0000004d',
        colorBgContainer: '#ffffff',
        colorBgLayout: '#ffffff',
        wireframe: false,
        colorTextBase: '#202d40',
        colorPrimaryBgHover: '#0065fd1f',
        colorFill: '#f7f9fe',
    },
    components: {
        Table: {
            headerBg: '#FFFFFF',
            rowHoverBg: '#f7f9fe',
            borderColor: COLORS.NEUTRAL.N7,
            colorText: COLORS.NEUTRAL.N2,
            headerColor: COLORS.NEUTRAL.N3,
        },
        Form: {
            verticalLabelPadding: 4,
            labelColor: COLORS.NEUTRAL.N2,
        },
        Tooltip: {
            colorTextLightSolid: '#4C576C',
        },
        Tree: {
            titleHeight: 32,
            nodeHoverBg: 'rgba(229, 240, 255, 0.8)',
            nodeSelectedBg: 'rgba(229, 240, 255, 0.6)',
        },
        DatePicker: {
            colorBgElevated: '#0a1b40',
            colorBgContainer: '#0a1b40',
            colorText: '#00000A',
        },
        Modal: {
            colorBgMask: 'rgba(0, 0, 10, 1)',
            colorBgElevated: '#3F3F45',
            titleColor: '#FFFFFF',
            colorText: '#FFFFFF',
        },
        Popover: {
            colorBgElevated: 'rgba(255, 255, 255, 0.60)',
            borderRadius: 4,
        },
        Layout: {
            lightSiderBg: 'transparent',
        },
        TreeSelect: {
            colorText: COLORS.NEUTRAL.N2,
            nodeHoverBg: COLORS.BRAND.B1,
            nodeSelectedBg: COLORS.BRAND.B2,
        },
        InputNumber: {
            colorText: COLORS.NEUTRAL.N2,
            colorBorder: COLORS.NEUTRAL.N7,
            hoverBorderColor: COLORS.BRAND.B7,
        },
    },
    algorithm: theme.defaultAlgorithm,
};
